spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/hackathon?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  header: Authorization
  prefix: Bearer
  secret: ${SECRET:fewbhauifaewhui}
  accessExpiration: 271000
  refreshExpiration: 604800
redis:
  host: ${REDIS_HOST:localhost}
  port: 6379

server:
  port: 8080

coolsms:
  apikey: NCSYKPAWFVP4H6JW
  apisecret: SNVSNOIINOLQMJGCYNEQPEQUHOVYSD6W
  fromnumber: 010-5706-2562