spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/hackathon?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  header: Authorization
  prefix: Bearer
  secret: ${SECRET}
  accessExpiration: 271000
  refreshExpiration: 604800
redis:
  host: ${REDIS_HOST:localhost}
  port: 6379
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: daedong
    region:
      static: ap-northeast-2
  stack:
    auto: false

server:
  port: 8080
  servlet:
    context-path: /founderz

coolsms:
  apikey: ${API_KEY}
  apisecret: ${API_SECRET}
  fromnumber: ${PHONE_NUMBER}